### ISSUE TITLE
About sdxl

### ISSUE THREAD

**Issue by YuehengLuo** [SPRIGHT-T2I/SPRIGHT#8]
Thanks for your work! Have you tried using sdxl to fine-tune your dataset SPRIGHT?

**Comment by agneet42** [comment]
Hi @YuehengLuo, no we did not fine-tune SDXL in our experiments. However, we did perform an experiment where we fine-tuned PixArt-Sigma and attained a score of 0.2501. We did not optimize any hyper-parameters.

**Comment by YuehengLuo** [comment]
Thanks for your quick response! I understand.
